### ISSUE TITLE
proxy 502 error (2 mn timeout) feature.microbiome (fir, qa stack) client using compute service /eda/computes/betadiv

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-eda-compute#41]
Feb 3 2023 FUT on this.
 
Feb 1 2023: Dan B. complained in microbiome channel: https://epvb.slack.com/archives/CBLPK9ZD3/p1675300369545239?thread_ts=1675259066.777149&cid=CBLPK9ZD3
seemed a fluke,  it worked when he tried again almost immediately.

The client got a proxy error 502 on referrer: 
https://feature.microbiomedb.org/mbio.feature/app/workspace/analyses/DS_ca4404e155/luprQIi/visualizations/ihzy8/02af4188-e4f0-4565-97c5-b8aeaf35d83e
(we got error email)

(file names here correspond to log file names)
Attached the proxy error in the website apache logs. 
Attached the unfinished request in the compute logs.

[ var_log_containers_docker_eda_qa_compute_1-feb3-2023.txt](https://github.com/VEuPathDB/service-eda-compute/files/10582357/var_log_containers_docker_eda_qa_compute_1-feb3-2023.txt)
[etc-httpd_logs_feature_microbiomedb_org_errorlog.txt](https://github.com/VEuPathDB/service-eda-compute/files/10582359/etc-httpd_logs_feature_microbiomedb_org_errorlog.txt)

**Comment by Foxcapades** [comment]
What server is this from?  I would like to see the logs of the dataset access service for this request as well.

**Comment by Foxcapades** [comment]
It appears the actual underlying error is in the dataset access service which seems to have fairly regular issues connecting to the target SQL database:

```
2023-02-01 20:21:45.839 [rid:1mmcj] DEBUG PoolableConnectionFactory:675 - Failed to validate a poolable connection.
java.sql.SQLRecoverableException: IO Error: Host is unreachable
        at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1061) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1104) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1425) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1308) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3745) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3854) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1097) ~[service.jar:3.0.0]
        at org.apache.commons.dbcp2.PoolableConnection.validate(PoolableConnection.java:351) ~[service.jar:3.0.0]
        at org.apache.commons.dbcp2.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:653) ~[service.jar:3.0.0]
        at org.apache.commons.dbcp2.PoolableConnectionFactory.validateObject(PoolableConnectionFactory.java:671) ~[service.jar:3.0.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:350) ~[service.jar:3.0.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428) ~[service.jar:3.0.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232) ~[service.jar:3.0.0]
        at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:141) ~[service.jar:3.0.0]
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.db.wrapper.AbstractDataSourceWrapper.getConnection(AbstractDataSourceWrapper.java:31) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.db.wrapper.DataSourceWrapper.lambda$getConnection$0(DataSourceWrapper.java:43) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.db.wrapper.DataSourceWrapper.checkExhaustedPool(DataSourceWrapper.java:54) ~[service.jar:3.0.0]
        at org.gusdb.fgputil.db.wrapper.DataSourceWrapper.getConnection(DataSourceWrapper.java:42) ~[service.jar:3.0.0]
        at io.vulpine.lib.query.util.query.QueryBase.getConnection(QueryBase.java:157) ~[service.jar:3.0.0]
        at io.vulpine.lib.query.util.query.QueryImpl.execute(QueryImpl.java:64) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.repo.UserRepo$Select.guestUserByID(UserRepo.java:23) ~[service.jar:3.0.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.AuthFilter.filter(AuthFilter.java:123) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44) ~[service.jar:3.0.0]
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[service.jar:3.0.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) ~[service.jar:3.0.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[service.jar:3.0.0]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.io.IOException: Host is unreachable
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:245) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:417) ~[?:?]
        at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415) ~[service.jar:3.0.0]
        at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118) ~[service.jar:3.0.0]
        at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266) ~[service.jar:3.0.0]
        at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198) ~[service.jar:3.0.0]
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140) ~[service.jar:3.0.0]
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113) ~[service.jar:3.0.0]
        at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97) ~[service.jar:3.0.0]
        at oracle.net.ano.CryptoNIONSDataChannel.readDataFromSocketChannel(Unknown Source) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:497) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:151) ~[service.jar:3.0.0]
        at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1051) ~[service.jar:3.0.0]
        ... 39 more
```

**Comment by aurreco-uga** [comment]
old
