### ISSUE TITLE
Warning state from MinIO java client causing NPE in compute.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-eda-compute#78]
```
eda_local-compute-1               | 2023-11-27 14:46:39.304 [rid:     ][jid:3badba9c2faac99d8792149ea24999f9][p:correlationassayassay] DEBUG BucketObjectContainer:481 - Attempting to upload file '/tmp/workspaces/3badba9c2faac99d8792149ea24999f9/output-stats' to path '3badba9c2faac99d8792149ea24999f9/output-stats' in Bucket{ name='dev-bucket' }
eda_local-compute-1               | Nov 27, 2023 2:46:40 PM io.minio.S3Base lambda$completeMultipartUploadAsync$12
eda_local-compute-1               | WARNING: S3 service returned unknown XML for CompleteMultipartUpload REST API. <?xml version="1.0" encoding="UTF-8"?>
eda_local-compute-1               | <CompleteMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Location>http://minio:9000/dev-bucket/3badba9c2faac99d8792149ea24999f9/output-stats</Location><Bucket>dev-bucket</Bucket><Key>3badba9c2faac99d8792149ea24999f9/output-stats</Key><ETag>&#34;fbe34a5ab9559c5acb3fbaff9ad2978e-12&#34;</ETag><ChecksumCRC32></ChecksumCRC32><ChecksumCRC32C></ChecksumCRC32C><ChecksumSHA1></ChecksumSHA1><ChecksumSHA256></ChecksumSHA256></CompleteMultipartUploadResult>
eda_local-compute-1               | 2023-11-27 14:46:40.022 [rid:     ][jid:3badba9c2faac99d8792149ea24999f9][p:correlationassayassay] ERROR QueueWrapper:100 - job execution failed with an exception for job 3badba9c2faac99d8792149ea24999f9
eda_local-compute-1               |  java.lang.NullPointerException: res.etag() must not be null
eda_local-compute-1               | 	at org.veupathdb.lib.s3.s34k.minio.BucketObjectContainer.upload(BucketObjectContainer.kt:497) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.s3.s34k.core.objects.AbstractObjectContainer.upload(AbstractObjectContainer.kt:124) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.s3.workspaces.impl.S3WorkspaceImpl.copy(S3WorkspaceImpl.kt:32) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.compute.platform.intern.s3.S3.persistFile(S3.kt:107) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.compute.platform.intern.s3.S3.persistFile$default(S3.kt:100) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.compute.platform.intern.s3.S3.persistFiles(S3.kt:96) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.compute.platform.intern.jobs.JobExecutionHandler.execute(JobExecutionHandler.kt:101) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.compute.platform.intern.queues.QueueWrapper.onJob(QueueWrapper.kt:94) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.compute.platform.intern.queues.QueueWrapper.access$onJob(QueueWrapper.kt:30) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.compute.platform.intern.queues.QueueWrapper$3.handle(QueueWrapper.kt:61) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.rabbit.jobs.pools.JobHandlers.execute(JobHandlers.kt:18) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at org.veupathdb.lib.rabbit.jobs.QueueWorker.initCallbacks$lambda-5$lambda-3$lambda-2(QueueWorker.kt:82) ~[service.jar:1.0.0]
eda_local-compute-1               | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
eda_local-compute-1               | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
eda_local-compute-1               | 	at java.lang.Thread.run(Thread.java:833) [?:?]
eda_local-compute-1               | 2023-11-27 14:46:40.026 [rid:     ][jid:3badba9c2faac99d8792149ea24999f9][p:correlationassayassay] DEBUG QueueWorker:55 - sending error notification ErrorNotification: {
eda_local-compute-1               |   "jobID" : "3badba9c2faac99d8792149ea24999f9",
eda_local-compute-1               |   "code" : 1,
eda_local-compute-1               |   "message" : "res.etag() must not be null"
eda_local-compute-1               | }
```

Not sure why the MinIO client is failing to parse the response or why it considers this a warning rather than an error.

**Comment by Foxcapades** [comment]
**Root cause**:

https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/S3Base.java#L2005 is incompatible with the Kotlin type definition at https://github.com/VEuPathDB/lib-s34k/blob/main/src/main/kotlin/org/veupathdb/lib/s3/s34k/objects/S3Object.kt#L32

Kotlin is expecting that field to be non-nullable, but it is being passed a null value.
