### ISSUE TITLE
Investigate how compute job was stuck in "queued"

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/service-eda-compute#88]
Job config:
```
{"config":{"collectionVariable":{"entityId":"EUPATH_0000813","collectionId":"EUPATH_0009256"},"rankingMethod":"variance"},"derivedVariables":[],"filters":[],"studyId":"Bangladesh_healthy_5yr-1"}
```

Time: Feb 29, 2024: 10 AM EST

Exception when job was submitted:

```
ESC[mESC[33m2024-02-29 10:30:34.047 [rid:71PCY][jid:][p:] WARN  ErrorMapper:70 - Caught Exception:
ESC[m org.veupathdb.lib.s3.s34k.errors.S34KError: Failed to test if object '31354285b5cf4901bce52b489ab80040/.workspace' exists in Bucket{ name='eda-compute-prod' }
        at org.veupathdb.lib.s3.s34k.minio.operations.Simple_object_opsKt.ObjectExists(simple-object-ops.kt:153) ~[service.jar:1.0.0]
        at org.veupathdb.lib.s3.s34k.minio.BucketObjectContainer.contains(BucketObjectContainer.kt:36) ~[service.jar:1.0.0]
        at org.veupathdb.lib.s3.s34k.core.objects.AbstractObjectContainer.contains(AbstractObjectContainer.kt:21) ~[service.jar:1.0.0]
        at org.veupathdb.lib.s3.workspaces.S3WorkspaceFactory.create(S3WorkspaceFactory.kt:151) ~[service.jar:1.0.0]
        at org.veupathdb.lib.compute.platform.intern.s3.S3.submitWorkspace(S3.kt:271) ~[service.jar:1.0.0]
        at org.veupathdb.lib.compute.platform.AsyncPlatform.submitJob(AsyncPlatform.kt:177) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.compute.EDA.getOrSubmitComputeJob(EDA.kt:220) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.compute.controller.ComputeController.submitJob(ComputeController.java:247) ~[service.jar:1.0.0]
        at org.veupathdb.service.eda.compute.controller.ComputeController.postComputesRankedabundance(ComputeController.java:115) ~[service.jar:1.0.0]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:1.0.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) [service.jar:1.0.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) [service.jar:1.0.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) [service.jar:1.0.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) [service.jar:1.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) [service.jar:1.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) [service.jar:1.0.0]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.minio.errors.ServerException: server failed with HTTP status code 500
        at io.minio.S3Base$1.onResponse(S3Base.java:725) ~[service.jar:1.0.0]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[service.jar:1.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        ... 1 more
```

**Comment by dmgaldi** [comment]
For all logs related to this job
```
ssh dgaldi@watermelon.uga.apidb.org zgrep "31354285b5cf4901bce52b489ab80040" /var/log/containers/archive/docker.eda_prod_compute_1.log-20240301.gz | less
```
