### ISSUE TITLE
UD (biom user dataset) : alpha div plugin is missing rows

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/service-eda-compute#93]
We recently ran into the following exception in compute service:

```
ESC[m java.lang.IllegalStateException: Computed row entity ID 'S21_MBD1_R (Source) does not match expected ID S21_MBD1_P (Source)
        at org.veupathdb.service.eda.ms.core.stream.RootStreamingEntityNode.applyCompute(RootStreamingEntityNode.java:162) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ms.core.stream.RootStreamingEntityNode.lambda$next$7(RootStreamingEntityNode.java:139) ~[service.jar:3.0.0]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.veupathdb.service.eda.ms.core.stream.RootStreamingEntityNode.next(RootStreamingEntityNode.java:139) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ms.core.stream.RootStreamingEntityNode.next(RootStreamingEntityNode.java:37) ~[service.jar:3.0.0]
```
That exception would be caused by some rows being excluded by the compute. Here's the output of the compute service:

[compute-output.txt](https://github.com/VEuPathDB/service-eda-compute/files/14828325/compute-output.txt)

Request: `http://compute-internal:80/computes/alphadiv/tabular`

```
{
    "studyId": "auto_20240401135637_c7hT-1",
    "filters": [],
    "derivedVariables": [],
    "config": {
        "collectionVariable": {
            "entityId": "MBIOTEMP_Source",
            "collectionId": "EUPATH_0009256"
        },
        "alphaDivMethod": "simpson"
    }
}
```

**Comment by aurreco-uga** [comment]
@asizemore : i shared https://microbiomedb.org/mbio/app/workspace/datasets/4107938 with your account ablevins@apidb.org
so u can reproduce. 

![Image](https://github.com/VEuPathDB/service-eda-compute/assets/16354313/53802984-7de4-4784-a0b7-6a8c6537aedc)

**Comment by asizemore** [comment]
Looks like it's happening for alpha diversity, beta diversity, and ranked abundance. Correlation and differential abundance look fine. The difference between these two groups of apps is the first three apps use the /tabular endpoint for data and the final two use /stats. Not sure if this is the real driver of the bug yet but that's what i've found so far!

**Comment by asizemore** [comment]
oh it's probably that some of their samples have 0s for all taxa. We exclude these samples. I'll take a look though to confirm

**Comment by aurreco-uga** [comment]
Dan explains: Some computes don't always return a row for every ID which merging service expects.
 It's by design but Ann suggested there's not a good way to return a row for some IDs due to the nature of the user data.
